name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: amaldinesh7/extract-substring@master
        with:
          content: "Find me with in the text"
          delimiterOne: "me"
          delimiterTwo: "text"

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.match }}" == "with in the"
